### ISSUE TITLE
Might be worth a look

### ISSUE THREAD

**Issue by mainrs** [encody/autoruby#1]
Hey! 

Ive been trying to port https://github.com/tshatrov/ichiran/ to Rust previously. It's a segmentation tool as well but is incredible fast and contains a lot of hand tweaked edge cases.

I had trouble understanding the lisp code that queries the database. But I managed to port the database from postgres to SQLite. If one would be able to understand and reimplements the query logic in Rust we would have a cool library that can be embedded into other applications fairly easily!

The tool can be tried at ichi.moe

**Comment by encody** [comment]
It's kind of ironic, given the blog post I just wrote about this tool using SQLite, but today I experimented with embedding the dictionary directly in the binary, so there's no need for any sort of SQL, and it's _way_ faster. Like 250x faster. So, I think I might be going that direction with this project in the future, because I eventually want to target WASM, and then make a browser extension.

Cool to hear about this project, though. I hadn't heard of it before.
